namespace: '\front\controllers\'
routes:
  home:
    path: '/'
    controller: 'defaultController::indexAction'
    methods: 'GET'
  subscribe:
    path: '/subscribe'
    controller: 'defaultController::subscribeAction'
    methods: 'POST'